const theme = {
  "*": { fontFamily: "'Urbanist', sans-serif", color: "#ccc" },
  body: { backgroundColor: "#171717" },
  ":root": { "--animate-delay": "0s" },
  "input:active": { outline: "none", border: "none" },
  ".header img": {
    height: "24px",
    margin: "-10px",
    marginBottom: "-45px",
    padding: "15px",
    transition: ".5s all",
  },
  ".header img:hover": {
    cursor: "pointer",
    backgroundColor: "white",
    borderRadius: "5px",
    boxShadow: "0px 0px 15px -5px rgba(0,0,0,0.25)",
  },
  ".icon-bar": { fontSize: "20px" },
  ".keyboard-outline": {
    margin: "0",
    height: "30px",
    paddingLeft: "10px",
    paddingRight: "10px",
    textAlign: "center",
    lineHeight: "30px",
    borderRadius: "4px",
    minWidth: "10px",
    color: "#aaa",
    border: "2px solid #aaa",
    background: "#333",
    marginRight: "10px",
    fontSize: "16px",
  },
  ".courses": {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    width: "90%",
    maxWidth: "1500px",
    margin: "0 auto",
    paddingTop: "10px",
    paddingLeft: "10px",
    paddingRight: "10px",
    gridGap: "20px",
    marginBottom: "50px",
  },
  ".courses-list": {
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    width: "90%",
    maxWidth: "1500px",
    margin: "0 auto",
    paddingTop: "10px",
    paddingLeft: "10px",
    paddingRight: "10px",
    gridGap: "20px",
    marginBottom: "50px",
  },
  ".course": {
    padding: "25px",
    border: "1px solid #333",
    borderRadius: "8px",
    backgroundColor: "#222",
    transition: ".3s all",
  },
  ".course:hover": {
    cursor: "pointer",
    boxShadow: "0px 0px 35px -5px rgba(0,0,0,0.25)",
    border: "1px solid #888",
  },
  ".content": {
    display: "flex",
    width: "95%",
    position: "relative",
    overflow: "auto",
    flexDirection: "column",
    transition: ".3s all",
  },
  ".content::-webkit-scrollbar, html::-webkit-scrollbar, .right::-webkit-scrollbar, .courses::-webkit-scrollbar":
    {
      display: "none",
    },
  ".container": {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
  },
  ".right": {
    width: "35%",
    minWidth: "400px",
    position: ["-webkit-sticky", "sticky"],
    top: "0",
    transition: ".2s all",
    height: "100vh",
    padding: "25px",
    background: "#171717",
    overflow: "scroll",
    boxShadow: "-10px 0px 20px -4px rgba(255,255,255,0.1)",
  },
  ".course-top": {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "3px",
  },
  ".course-top h3": {
    margin: "0px",
    padding: "0px",
    fontSize: "16px",
    textAlign: "left",
    color: "#aaa",
  },
  ".course-icons": {
    display: "grid",
    gridTemplateColumns: "1.65fr 1fr",
    marginTop: "15px",
  },
  ".course h2": { margin: "0", marginTop: "5px", marginBottom: "5px" },
  ".course-icon": {
    margin: "0",
    padding: "0",
    minWidth: "25%",
    display: "flex",
    marginRight: "20px",
    paddingBottom: "5px",
    alignItems: "center",
  },
  ".course-icon img": { width: "20px", filter: "brightness(0) invert(1)" },
  ".course-icon p": { margin: "0", padding: "5px" },
  ".course-icon a": {
    textDecoration: "none",
    padding: "5px",
    borderRadius: "2px",
    color: "#ccc",
    transition: ".3s all",
    display: "flex",
    alignItems: "center",
  },
  ".course-icon a:hover": {
    background: "#444",
    boxShadow: "0px 0px 10px -2px rgba(0,0,0,0.5)",
  },
  ".loader-container": {
    display: "flex",
    marginTop: "30px",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  ".color-circle-green": {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    marginLeft: "5px",
    background: "green",
  },
  ".color-circle-yellow": {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    marginLeft: "5px",
    background: "orange",
  },
  ".color-circle-red": {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    marginLeft: "5px",
    background: "red",
  },
  ".large-text": { fontSize: "18px", fontWeight: 600 },
  ".small-text": { fontSize: "12px" },
  ".searchFields": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "95%",
    margin: "0 auto",
  },
  ".instructor-rating": {
    padding: "10px",
    margin: "0",
    marginLeft: "5px",
    background: "green",
    borderRadius: "3px",
    color: "white",
  },
  ".header": {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "start",
    width: "fit-content",
    margin: "0 auto",
    paddingTop: "50px",
  },
  ".header h1": { fontSize: "48px" },
  ".main-subtitle": {
    textAlign: "center",
    paddingTop: "20px",
    paddingBottom: "20px",
    marginLeft: "5px",
  },
  ".app-subtitle": {
    fontSize: "20px",
    padding: "0",
    margin: "0 auto",
    marginTop: "-20px",
    marginBottom: "40px",
    width: "90%",
    maxWidth: "800px",
    fontWeight: "lighter",
    textAlign: "center",
  },
  ".course h5": {
    fontSize: "16px",
    padding: "0",
    margin: "0",
    fontWeight: "lighter",
    width: "50%",
    textAlign: "right",
  },
  ".course h6": {
    fontWeight: "lighter",
    margin: "0",
    marginBottom: "10px",
    fontSize: "14px",
  },
  ".selected-courses": {
    display: "grid",
    gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
    gridGap: "20px",
    marginBottom: "50px",
  },
  ".select-field": {
    width: "350px",
    marginRight: "10px",
    fontWeight: "bolder",
  },
  ".wrapper-input": {
    position: "relative",
    width: "100%",
    maxWidth: "700px",
    marginRight: "40px",
  },
  ".input-logo": {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    right: "-10px",
    fontSize: "20px",
    color: "#aaa",
  },
  ".main-input": {
    padding: "0",
    height: "60px",
    paddingLeft: "30px",
    margin: "5px",
    width: "100%",
    color: "white",
    border: "1px solid #333",
    borderRadius: "8px",
    backgroundColor: "#222",
    fontSize: "18px",
    fontWeight: "bold",
    boxShadow: "0px 0px 100px 20px rgba(255,255,255,0.25)",
  },
  ".settings": {
    paddingLeft: "20px",
    paddingRight: "20px",
    height: "70px",
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    background: "#462593",
    fontSize: "16px",
    color: "white",
    boxShadow: "0px 0px 25px 0px rgba(0,0,0,0.25)",
    border: "0",
    borderRadius: "5px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  ".settings p": { marginLeft: "10px" },
  ".course-attributes": {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: "10px",
  },
  ".course-attribute": {
    borderRadius: "2px",
    marginRight: "10px",
    padding: "5px",
    background: "#333",
    fontSize: "12px",
  },
  ".course-alert": {
    display: "flex",
    backgroundColor: "#333",
    alignItems: "center",
    padding: "10px",
    marginTop: "10px",
    justifyContent: "start",
  },
  ".course-warning": {
    display: "flex",
    borderRadius: "3px",
    backgroundColor: "#333",
    alignItems: "center",
    marginTop: "10px",
    padding: "10px",
    justifyContent: "start",
  },
  ".course-warning img": {
    filter:
      "invert(68%) sepia(3%) saturate(2714%) hue-rotate(314deg) brightness(121%) contrast(99%)",
  },
  ".course-alert img": {
    filter:
      "invert(94%) sepia(8%) saturate(2028%) hue-rotate(326deg) brightness(101%) contrast(108%)",
  },
  ".course-alert p": { color: "#FFE5A3" },
  ".course-warning p": { color: "#FEC4C1" },
  ".course-alert p, .course-warning p": {
    margin: "0",
    marginLeft: ["5px", "10px"],
    padding: "0",
    fontSize: "14px",
    fontWeight: "bold",
  },
  ".react-toggle": {
    touchAction: "pan-x",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    backgroundColor: "transparent",
    border: "0",
    padding: "0",
    WebkitTouchCallout: "none",
    WebkitUserSelect: "none",
    KhtmlUserSelect: "none",
    MozUserSelect: "none",
    msUserSelect: "none",
    userSelect: "none",
    WebkitTapHighlightColor: ["rgba(0,0,0,0)", "transparent"],
  },
  ".react-toggle-screenreader-only": {
    border: "0",
    clip: "rect(0 0 0 0)",
    height: "1px",
    margin: "-1px",
    overflow: "hidden",
    padding: "0",
    position: "absolute",
    width: "1px",
  },
  ".react-toggle--disabled": {
    cursor: "not-allowed",
    opacity: 0.5,
    WebkitTransition: "opacity 0.25s",
    transition: "opacity 0.25s",
  },
  ".react-toggle-track": {
    width: "50px",
    height: "24px",
    padding: "0",
    borderRadius: "30px",
    backgroundColor: "#4D4D4D",
    WebkitTransition: "all 0.2s ease",
    MozTransition: "all 0.2s ease",
    transition: "all 0.2s ease",
  },
  ".react-toggle:hover:not(.react-toggle--disabled) .react-toggle-track": {
    backgroundColor: "#000000",
  },
  ".react-toggle--checked .react-toggle-track": { backgroundColor: "#19AB27" },
  ".react-toggle--checked:hover:not(.react-toggle--disabled) .react-toggle-track":
    {
      backgroundColor: "#128D15",
    },
  ".react-toggle-track-check": {
    position: "absolute",
    width: "14px",
    height: "10px",
    top: "0px",
    bottom: "0px",
    marginTop: "auto",
    marginBottom: "auto",
    lineHeight: 0,
    left: "8px",
    opacity: 0,
    WebkitTransition: "opacity 0.25s ease",
    MozTransition: "opacity 0.25s ease",
    transition: "opacity 0.25s ease",
  },
  ".react-toggle--checked .react-toggle-track-check": {
    opacity: 1,
    WebkitTransition: "opacity 0.25s ease",
    MozTransition: "opacity 0.25s ease",
    transition: "opacity 0.25s ease",
  },
  ".react-toggle-track-x": {
    position: "absolute",
    width: "10px",
    height: "10px",
    top: "0px",
    bottom: "0px",
    marginTop: "auto",
    marginBottom: "auto",
    lineHeight: 0,
    right: "10px",
    opacity: 1,
    WebkitTransition: "opacity 0.25s ease",
    MozTransition: "opacity 0.25s ease",
    transition: "opacity 0.25s ease",
  },
  ".react-toggle--checked .react-toggle-track-x": { opacity: 0 },
  ".react-toggle-thumb": {
    transition: [
      "all 0.5s cubic-bezier(0.23, 1, 0.32, 1) 0ms",
      "all 0.25s ease",
    ],
    position: "absolute",
    top: "1px",
    left: "1px",
    width: "22px",
    height: "22px",
    border: "1px solid #4D4D4D",
    borderRadius: "50%",
    backgroundColor: "#FAFAFA",
    WebkitBoxSizing: "border-box",
    MozBoxSizing: "border-box",
    boxSizing: "border-box",
    WebkitTransition: "all 0.25s ease",
    MozTransition: "all 0.25s ease",
  },
  ".react-toggle--checked .react-toggle-thumb": {
    left: "27px",
    borderColor: "#19AB27",
  },
  ".react-toggle--focus .react-toggle-thumb": {
    WebkitBoxShadow: "0px 0px 3px 2px #0099E0",
    MozBoxShadow: "0px 0px 3px 2px #0099E0",
    boxShadow: "0px 0px 2px 3px #0099E0",
  },
  ".react-toggle:active:not(.react-toggle--disabled) .react-toggle-thumb": {
    WebkitBoxShadow: "0px 0px 5px 5px #0099E0",
    MozBoxShadow: "0px 0px 5px 5px #0099E0",
    boxShadow: "0px 0px 5px 5px #0099E0",
  },
  ".options": {
    width: "fit-content",
    margin: "0 auto",
    marginTop: "50px",
    backgroundColor: "#333",
    borderRadius: "10px",
    padding: "70px 100px",
    boxShadow: "0px 0px 155px 5px rgba(0,0,0,0.25)",
  },
  ".react-loader": {
    padding: "100px",
    width: "fit-content",
    marginTop: "450px",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: "10px",
  },
  ".app-settings-subtitle": { marginTop: "-20px", fontSize: "18px" },
  ".options h5": {
    fontSize: "16px",
    margin: "0",
    marginBottom: "10px",
    marginTop: "10px",
    fontWeight: 600,
  },
  ".options-content": {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "start",
  },
  ".option-button": { display: "none" },
  ".options-content-left": { width: "fit-content", marginRight: "100px" },
  ".options-content-middle": {
    marginLeft: "20px",
    marginRight: "20px",
    width: "40%",
  },
  ".options-header": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    width: "fit-content",
  },
  ".options h2": {
    marginBottom: "0px",
    marginRight: "25px",
    marginTop: "0px",
    fontSize: "30px",
  },
  ".options-header p": { marginRight: "10px" },
  ".options h3": {},
  ".option": { display: "flex", alignItems: "center" },
  ".option p": { marginRight: "10px" },
  ".extra-padding": { paddingTop: "5px", paddingBottom: "5px" },
  h1: { fontSize: "40px", padding: "10px" },
  ".toggle_modal": {
    border: "1px solid #555",
    background: "white",
    padding: "10px 30px",
    margin: "0 auto",
    marginTop: "20px",
    display: "block",
    transition: ".3s all",
  },
  ".toggle_modal:hover": {
    background: "#555",
    color: "white",
    cursor: "pointer",
  },
  ".introscreen-bg": {
    zIndex: 5,
    position: "fixed",
    top: "0",
    left: "0",
    width: "100%",
    margin: "0",
    padding: "0",
    height: "100vh",
    background: "rgba(50,50,50,0.2)",
    backdropFilter: "blur(5px)",
  },
  ".introscreen": {
    background: "#222",
    border: "1px solid #555",
    boxShadow: "0px 0px 115px -5px rgba(255,255,255,0.25)",
    display: "flex",
    flexDirection: "column",
    margin: "0 auto",
    marginTop: "70px",
    alignItems: "center",
    width: "80%",
    maxWidth: "1200px",
    borderRadius: "15px",
    padding: "50px",
  },
  ".introscreen-features": {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    width: "95%",
    maxWidth: "900px",
    gridGap: "10px",
    marginTop: "40px",
    marginBottom: "40px",
  },
  ".coming-soon": { border: "3px solid gold" },
  ".introscreen h3": { fontSize: "32px" },
  ".introscreen-feature": {
    display: "flex",
    alignItems: "center",
    borderRadius: "5px",
    padding: "30px",
    background: "#333",
  },
  ".introscreen-feature img": {
    width: "60px",
    height: "60px",
    marginRight: "20px",
    filter: "brightness(0) invert(1)",
  },
  ".introscreen-feature-text": {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  ".introscreen button": {
    border: "0",
    background: "#462593",
    color: "white",
    height: "60px",
    width: "90%",
    maxWidth: "400px",
    borderRadius: "5px",
    fontSize: "20px",
    fontWeight: "bolder",
    cursor: "pointer",
    transition: ".3s all",
  },
  ".introscreen button:hover": { background: "#4E2AA2" },
  ".introscreen-feature-text h4": { margin: "0", padding: "0" },
  ".introscreen-feature p": {
    margin: "0",
    padding: "0",
    marginTop: "5px",
    fontSize: "14px",
    fontWeight: "lighter",
  },
  ".introscreen h2": { fontSize: "32px", margin: "0", marginBottom: "15px" },
  ".introscreen h5": { margin: "0", fontWeight: "lighter", fontSize: "18px" },
  ".introscreen h6": { fontSize: "20px", textAlign: "center" },
  ".calendar-slot": {
    height: "10px",
    width: "100%",
    borderRadius: "1px",
    position: "relative",
  },
  ".calendar-tooltip": {
    position: "absolute",
    top: "0",
    background: "#333",
    boxShadow: "0px 0px 15px -5px rgba(0,0,0,0.25)",
    borderRadius: "5px",
    transition: ".3s all",
    padding: "15px",
    left: "0",
    zIndex: 1,
    opacity: 0,
    width: "100px",
  },
  ".calendar-tooltip h5, .calendar-tooltip h6": {
    margin: "0px",
    marginBottom: "5px",
  },
  ".calendar-slot:hover .calendar-tooltip": {
    cursor: "pointer",
    transition: ".1s all",
    opacity: 1,
  },
  ".border-top": { height: "9px", borderTop: "1px solid #666" },
  ".calendar-close": {
    position: "absolute",
    top: "10px",
    right: "10px",
    fontSize: "24px",
    padding: "10px",
    borderRadius: "3px",
    transition: ".1s all",
  },
  ".no-results": {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    width: "100%",
    fontSize: "20px",
    fontWeight: "lighter",
    color: "#666",
  },
  ".no-results p": { margin: "0", marginTop: "-15px", marginBottom: "10px" },
  ".no-results-content": {
    display: "flex",
    alignItems: "center",
    color: "#333",
  },
  ".no-results-content h6": { fontSize: "20px" },
  ".calendar-close:hover": {
    cursor: "pointer",
    background: "#444",
    boxShadow: "0px 0px 15px -5px rgba(0,0,0,0.25)",
  },
  ".calendar": {
    display: "flex",
    justifyContent: "center",
    boxShadow: "0px 0px 15px -5px rgba(0,0,0,0.25)",
    paddingTop: "25px",
    paddingLeft: "10px",
    paddingRight: "10px",
    paddingBottom: "25px",
  },
  ".right-subtitle": {
    margin: "0",
    marginTop: "-15px",
    marginBottom: "20px",
    padding: "0",
  },
  ".course-color": { height: "10px", width: "10%", marginBottom: "20px" },
  ".calendar-day": { margin: "2px", width: "calc((100% / 5))" },
  ".slot-label-column": {
    width: "10px",
    marginRight: "-2px",
    paddingRight: "2px",
  },
  ".slot-label": { textAlign: "right", width: "10px", fontSize: "10px" },
  ".slot-empty": { backgroundColor: "#333", transition: ".3s all" },
  ".slot-filled": { backgroundColor: "#49A7C5", transition: ".3s all" },
  ".calendar-list": {
    display: "flex",
    marginTop: "-10px",
    marginBottom: "10px",
  },
  ".calendar-item": {
    margin: "2px",
    padding: "5px 15px",
    fontSize: "22px",
    fontWeight: "lighter",
    cursor: "pointer",
    transition: ".3s all",
    borderRadius: "3px",
    border: "1px solid #ccc",
  },
  ".active-calendar": {
    background: "#555",
    color: "white",
    border: "1px solid #555",
    transition: ".3s all",
  },
  ".empty-calendar": {
    border: "1px solid #ccc",
    padding: "100px 10px",
    marginTop: "-50px",
    textAlign: "center",
    color: "#888",
    transition: ".3s all",
    borderRadius: "10px",
  },
  ".calendar-item h6": {
    margin: "0",
    padding: "0",
    marginLeft: "5px",
    textAlign: "center",
    marginRight: "5px",
  },
  ".calendar-item:hover": { background: "#444", transition: ".3s all" },
  ".active-calendar:hover": {
    background: "#555",
    color: "white",
    border: "1px solid #555",
    transition: ".3s all",
  },
  ".calendar-item p": {
    margin: "0",
    padding: "0",
    marginLeft: "5px",
    marginRight: "5px",
    fontSize: "14px",
    fontWeight: "lighter",
    textAlign: "center",
  },
  ".calendar-day p": {
    margin: "0",
    marginBottom: "5px",
    fontSize: "12px",
    textAlign: "center",
    background: "#333",
    paddingTop: "5px",
    paddingBottom: "5px",
  },
  ".time-select": { height: "50px", width: "100%" },
  ".time-options": {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gridGap: "10px",
    marginTop: "15px",
  },
  ".time-options h5": { margin: "0" },
  ".courses-found": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "20px",
  },
  ".mobile-calendar": { display: "none" },
  "@media screen and (max-width: 1500px)": {
    ".courses": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
  },
  "@media screen and (max-width: 1000px)": {
    ".icons": { display: "none" },
    ".right": {
      position: "fixed",
      width: "90%",
      borderRadius: "20px",
      height: "100vh",
    },
    ".mobile-calendar": {
      position: "fixed",
      zIndex: 15,
      bottom: "30px",
      right: "15px",
      display: "flex",
      alignItems: "center",
      background: "#555",
      padding: "0px 15px",
      borderRadius: "999px",
      color: "white",
      fontSize: "18px",
    },
    ".mobile-calendar p": {
      marginLeft: "10px",
      fontWeight: "bold",
      fontSize: "16px",
    },
    ".introscreen": { padding: "30px" },
  },
  "@media screen and (max-width: 850px)": {
    ".introscreen-feature-text p": { display: "none" },
    ".introscreen-feature img": { width: "40px", height: "40px" },
    ".introscreen h6": { fontSize: "16px" },
  },
  "@media screen and (max-width: 700px)": {
    ".course-icons": { gridTemplateColumns: "1fr" },
    ".course-top": { flexDirection: "column-reverse" },
    ".course-top h5": { textAlign: "left" },
    ".course-top h3": { fontSize: "16px" },
    ".course h2": { fontSize: "20px" },
    ".searchFields": {
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      width: "95%",
      margin: "0 auto",
    },
    ".wrapper-input": { width: "90%" },
    ".main-input": { paddingLeft: "30px" },
    'input[type="text"], .select-field, .settings': { marginTop: "10px" },
    ".no-results-content": { display: "none" },
    ".settings": {
      position: "fixed",
      bottom: "30px",
      left: "15px",
      width: "fit-content",
      height: "fit-content",
      padding: "2px 15px",
      borderRadius: "999px",
      zIndex: 15,
    },
    ".calendar-list": { flexDirection: "column" },
    ".introscreen-feature": { padding: "10px" },
    ".keyboard-outline": { display: "none" },
    ".options-header p": { display: "none" },
    ".options-content": { width: "100%" },
    ".options-content-right": { display: "none" },
    ".options-content-left": { width: "100%", marginRight: "0" },
    ".options": {
      height: "calc(100vh - 100px)",
      padding: "50px 50px",
      marginTop: "0px",
      marginBottom: "0px",
      overflow: "scroll",
    },
    ".option-button": {
      display: "block",
      margin: "0 auto",
      marginTop: "20px",
      width: "100%",
      color: "#555",
      background: "white",
      paddingTop: "15px",
      paddingBottom: "15px",
      fontWeight: "bold",
      fontSize: "18px",
      border: "2px solid #555",
      borderRadius: "3px",
    },
  },
  "@media screen and (max-width: 500px)": {
    ".courses": { gridTemplateColumns: "1fr" },
    ".main-input": { fontSize: "14px" },
    ".introscreen-feature img": { width: "24px", height: "24px" },
    h1: { fontSize: "28px" },
    ".app-subtitle": { fontSize: "18px" },
  },
};

export default theme;
