name: update-courses
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  scrape-python:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - name: Run a one-line script
      run: python ./src/course_scraper.py
    - name: Committing changed files back to Github
      run: git config --global user.name 'Reed Uhlik'
    - name: Config property
      run: git config --global user.email 'reeduhlik@users.noreply.github.com'
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating courses"
    - name: push code to master
      run: git push
