name: update-courses
on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  scrape-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    - name: Switch to main branch
      run: git checkout main
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - name: Checkout main branch
      run: git checkout main
    - name: Run a scraping script
      run: python3 ./src/course_scraper.py
      env:
        GEORGETOWN_USERNAME: ${{ secrets.GEORGETOWN_USERNAME }}
        GEORGETOWN_PASSWORD: ${{ secrets.GEORGETOWN_PASSWORD }}
    - name: Committing changed files back to Github
      run: git config --global user.name 'Reed Uhlik'
    - name: Config property
      run: git config --global user.email 'reeduhlik@users.noreply.github.com'
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating courses"
    - name: push code to master
      run: git push
