name: update-courses
on: [push]
jobs:
  scrape-python:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - name: Run a one-line script
      run: python ./src/course_scraper.py
    - name: switching from HTTPS to SSH
      run: git remote set-url origin https://github.com/reeduhlik/class-finder.git
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating courses"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
