name: update-courses
on:
  schedule:
    - cron: "0 0,2,4,6,14,16,18,20,22, * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  scrape-python:
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: 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
        ref: ${{ github.head_ref }}
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - name: Checkout main branch
      run: git checkout main
    - name: Run a scraping script
      run: python ./src/course_scraper.py
    - name: Committing changed files back to Github
      run: git config --global user.name 'Reed Uhlik'
    - name: Config property
      run: git config --global user.email 'reeduhlik@users.noreply.github.com'
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating courses"
    - name: push code to master
      run: git push
